### ISSUE TITLE
App crashes in Android 5.1 devices when user tries to zoom-in beyond a certain extent in the map.

### ISSUE THREAD

**Issue by saitejamalapati** [react-native-maps/react-native-maps#3269]
We have come across a crash report with the below mentioned stack trace in our Application which is currently live:

```
Caused by java.lang.NullPointerException: Attempt to read from null array
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.g.a(g.java:56)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.a(ao.java:91)
       at com.google.maps.api.android.lib6.gmm6.store.fetch.i.a(i.java:99)
       at com.google.maps.api.android.lib6.gmm6.store.fetch.f.a(f.java:3)
       at com.google.maps.api.android.lib6.gmm6.store.j.a(j.java:19)
       at com.google.maps.api.android.lib6.gmm6.store.k.a(k.java:96)
       at com.google.maps.api.android.lib6.gmm6.store.k.d(k.java:164)
       at com.google.maps.api.android.lib6.gmm6.store.k.a(k.java:31)
       at com.google.maps.api.android.lib6.gmm6.store.f.handleMessage(f.java:100)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:218)
       at com.google.maps.api.android.lib6.gmm6.store.k.run(k.java:126)
       at com.google.maps.api.android.lib6.gmm6.store.ab.run(ab.java:12)
```

The crash has occurred in Android 5.1 (OPPO device). I have gone through other similar crashes reported by others and seems like all of them have reported in Android 5.1 devices. We have tested in other Android versions (8, 9 and 10) but were not able to reproduce it with the steps mentioned in those similar crash reports. We don't have any Android 5.1 devices with us. As per the discussions on other similar crashes, I have come to know that the crash has something to do with the zoom level exceeding 16 in those devices. In our application, we are using react-native-maps to show markers on the map. I have cross verified the logic of markers and it looks fine.

While browsing through the similar crashes I have come across one open issue with google on this. Here is the issue tracker link: https://issuetracker.google.com/issues/145941832

**Environment info:**
react: 16.8.3
react-native: 0.59.10
react-native-maps: 0.22.1

**Steps To Reproduce:**
1) Open maps in an Android 5.1 version device (Oppo / Lenovo / LG / Huawei devices preferable).
2) Try to zoom in beyond the maxZoomLevel of 16.

**Expected Behaviour:** 
The app shouldn't crash and user should be able to zoom in.

**Actual Behaviour:** 
The app crashes.

**Comment by somandubey** [comment]
+1, I have faced this issue too in current RN project.

**Comment by f4z3k4s** [comment]
+1, me also. Android 5.1 on Lenovo phone.

**Comment by andkom** [comment]
+1, also. Android 5.1 on Huawei Y6 Pro
