### ISSUE TITLE
App crashes when react-native-maps and react-native-geolocation-service modules are installed together

### ISSUE THREAD

**Issue by MihaiGitHub** [react-native-maps/react-native-maps#3294]
# Bug
react-native-maps does not work with react-native-geolocation-service module in the same project. App crashes on load. Once react-native-geolocation-service module is removed from the project, the app works fine.

react-native-geolocation-service is needed to get the users location, because it is more accurate than the javascript navigator object.

https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

## Environment info

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 7.14 GB / 15.95 GB
  Binaries:
    Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Library version
    react-native-maps => 0.26.1
    react-native-geolocation-service => ^4.0.0

## Steps To Reproduce

Sample app provided below which shows that the 2 modules don't work together as expected:

1. Download the sample app below, install dependencies, and try to run it.

https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

npm install
npm run android

Describe what you expected to happen:

1. App will crash on load.

## Reproducible sample code

https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

**Comment by rborn** [comment]
Can you add some logs with the crash? Give as much details as possible please

**Comment by anaszgh** [comment]
Any updates on this issue, i think i'm facing the same problem @MihaiGitHub did you find a solution?

**Comment by MihaiGitHub** [comment]
This is what I pulled from logkitty and a screenshot of what it looks like on the emulator:

```
$ react-native log-android
info Starting logkitty
[13:36:06] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[13:36:07] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()
                           └ ReactInstanceManager.recreateReactContextInBackground()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.runCreateReactContextOnNewThread()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[13:36:12] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[13:36:13] D | ReactNative ▶︎ ReactInstanceManager.detachViewFromInstance()

[13:36:21] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[13:36:21] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[13:36:26] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()

[13:36:26] D | ReactNative ▶︎ CatalystInstanceImpl.initialize()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[13:36:27] D | ReactNative ▶︎ ReactInstanceManager.detachViewFromInstance()
```
![image](https://user-images.githubusercontent.com/5934128/75069955-883e0f80-54af-11ea-9d9c-1c96fd66f5cc.png)

**Comment by rborn** [comment]
I don't find anything in these logs, what about some crash logs on your local dev device with logcat ? https://developer.android.com/studio/command-line/logcat

**Comment by jet2go** [comment]
MapView crashes in Android but works in local and App Store. Does anyone face with this issue before?
This is the version I'm using: "react-native-maps": "0.26.1"

**Comment by MihaiGitHub** [comment]
```
03-08 17:37:20.885 10050 10050 E asset   : setgid: Operation not permitted
03-08 17:37:24.066  1517  1533 E         : Couldn't opendir /data/app/vmdl1545708866.tmp: No such file or directory
03-08 17:37:24.066  1517  1533 E installd: Failed to delete /data/app/vmdl1545708866.tmp: No such file or directory
03-08 17:37:24.315 21322 21365 E GmsClient: unable to connect to service: com.google.android.gms.auth.key.retrieval.service.START on com.google.android.gms
03-08 17:37:24.894 28395 10004 E DeviceStateChecker: DeviceStateChecker cancelled
03-08 17:37:24.920 28395 28506 E AudioSource: Stop listening is called on already closed AudioSource
03-08 17:37:25.401  1448  1475 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-08 17:37:25.507  1448  1917 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-08 17:37:27.771 10112 10149 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-08 17:37:27.771 10112 10149 E AndroidRuntime: Process: com.reactnativemaps2, PID: 10112
03-08 17:37:27.771 10112 10149 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:60)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:40)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
03-08 17:37:27.771 10112 10149 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        ... 23 more
03-08 17:37:27.771 10112 10149 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        ... 23 more
03-08 17:37:27.771 10112 10149 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.reactnativemaps2-xX_eFvizAtM1RfqseMesZw==/base.apk"],nativeLibraryDirectories=[/data/app/com.reactnativemaps2-xX_eFvizAtM1RfqseMesZw==/lib/x86, /data/app/com.reactnativemaps2-xX_eFvizAtM1RfqseMesZw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-08 17:37:27.771 10112 10149 E AndroidRuntime:        ... 23 more
03-08 17:37:28.070  1448  1448 E EGL_emulation: tid 1448: eglCreateSyncKHR(1962): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-08 17:37:39.259  1640  1653 E memtrack: Couldn't load memtrack module

```

**Comment by Franky238** [comment]
Same problem here guys. Some news? Or quick fix?

**Comment by tylerthedeveloper** [comment]
I just ran into this as well - will try reverting to expected version

**Comment by xgenem** [comment]
Issue still presists.

**Comment by fillybrese** [comment]
@xgenem yeah i'm experiencing same
