### ISSUE TITLE
react native 0.59.9 pod installtion

### ISSUE THREAD

**Issue by ankitgauravapporio** [react-native-maps/react-native-maps#3462]
# Question

**Comment by ankitgauravapporio** [comment]
Hello every one , i am trying to install google map pods in version 0.59.9 of react native , but the pod installtion ends with error , and while running on device it stuck on splash screen

**Comment by ankitgauravapporio** [comment]
### Error

```
NoMethodError - undefined method `real_path' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project/object/container_item_proxy.rb:96:in `container_portal_annotation'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project/object/container_item_proxy.rb:105:in `to_hash_as'
