### ISSUE TITLE
ByteBufferAsIntBuffer  crash 

### ISSUE THREAD

**Issue by mohammadameer** [react-native-maps/react-native-maps#3550]
# Bug report

## Summary

we are getting this crash on Huawei and Samsung devices

```
Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array

java.nio.ByteBufferAsIntBuffer.put (ByteBufferAsIntBuffer.java:122)

com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.h.e (:com.google.android.gms.dynamite_mapsdynamite@203019083@20.30.19 (120408-0):8)
com.google.maps.api.android.lib6.gmm6.vector.av.run (:com.google.android.gms.dynamite_mapsdynamite@203019083@20.30.19 (120408-0):54)

```

![image](https://user-images.githubusercontent.com/35637666/93466479-968cc680-f8ec-11ea-8297-5e48664208c9.png)

## Environment info

`react-native info` output:

can't provide

Library version: 0.27.1

## Steps to reproduce

can't provide  

Describe what you expected to happen:

can't provide

## Reproducible sample code

can't provide

**Comment by mohammadameer** [comment]
screenshot for the crash from sentry
![image](https://user-images.githubusercontent.com/35637666/93512864-3d8d5480-f925-11ea-99a7-6350a6e676b7.png)

**Comment by mohammadameer** [comment]
we still getting this error tried to update the package to the last update but no fix I also found this 

https://stackoverflow.com/questions/27253524/attempt-to-get-length-of-null-array-in-google-maps-v2-android-app

is it relevant /

**Comment by james2m** [comment]
Plus one for this.

```
java.lang.NullPointerException: Attempt to get length of null array
        at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.g.m(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):6)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.g.k(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):1)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.af.t(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):8)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.t(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):14)
        at com.google.maps.api.android.lib6.gmm6.vector.bz.t(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):30)
        at com.google.maps.api.android.lib6.gmm6.vector.bs.c(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):144)
        at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@210214051@21.02.14 (040408-0):49)
```

**Comment by zishabei** [comment]
Same problem
```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.g.m(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):6)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.g.k(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):1)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.af.t(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):8)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.t(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):14)
       at com.google.maps.api.android.lib6.gmm6.vector.bz.t(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):30)
       at com.google.maps.api.android.lib6.gmm6.vector.bs.c(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):144)
       at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@210915083@21.09.15 (120408-0):49)
```

**Comment by martin-braun** [comment]
It's the same issue on Flutter, so it is really an internal issue of the Google Maps component. See https://github.com/flutter/flutter/issues/105965
