### ISSUE TITLE
Pod install error after after adding pod dependencies

### ISSUE THREAD

**Issue by Gabsys** [react-native-maps/react-native-maps#3874]
## Summary

Trying to install react-native-maps, everything works fine until I added
```
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```

After adding the above, running pod install gave me the below error:

```
RuntimeError - Compilation error generating constants :
	In file included from /var/folders/wh/dtc169_91t36bj8395_9zwkh0000gn/T/.const_generator20210703-45810-1gxdya3:1:
	In file included from /usr/local/include/stdio.h:64:
	/usr/local/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]`
```
## Environment info

      react-native-cli: 2.0.1
      react-native: 0.64.2
      react-native-maps: 0.28.0

`react-native info` output:
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 255.01 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1. `npm install react-native-maps --save-exact`
2. Add 
```
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
```
  above the use_native_modules! function.
3. run `pod install`

Describe what you expected to happen:
I expect the pod install to run successfully

Describe what you actually happens:
It shows error mentioned above

Full Error Showed:
```
RuntimeError - Compilation error generating constants :
	In file included from /var/folders/wh/dtc169_91t36bj8395_9zwkh0000gn/T/.const_generator20210703-45810-1gxdya3:1:
	In file included from /usr/local/include/stdio.h:64:
	/usr/local/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        unsigned char   *_base;
	                        ^
	/usr/local/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
	        unsigned char   *_base;
	                        ^
	                          _Nullable 
	/usr/local/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be null
	        unsigned char   *_base;
	                        ^
	                          _Nonnull 
	/usr/local/include/_stdio.h:138:32: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	/usr/local/include/_stdio.h:138:32: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:138:40: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	/usr/local/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	                                                   _Nullable
	/usr/local/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	                                                   _Nonnull
	/usr/local/include/_stdio.h:139:35: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	/usr/local/include/_stdio.h:139:35: note: insert '_Nullable' if the pointer may be null
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:139:35: note: insert '_Nonnull' if the pointer should never be null
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:140:32: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	/usr/local/include/_stdio.h:140:32: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:140:32: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:140:46: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	/usr/local/include/_stdio.h:140:46: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	                                                         _Nullable
	/usr/local/include/_stdio.h:140:46: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	                                                         _Nonnull
	/usr/local/include/_stdio.h:144:18: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	/usr/local/include/_stdio.h:144:18: note: insert '_Nullable' if the pointer may be null
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	                          _Nullable 
	/usr/local/include/_stdio.h:144:18: note: insert '_Nonnull' if the pointer should never be null
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	                          _Nonnull 
	In file included from /var/folders/wh/dtc169_91t36bj8395_9zwkh0000gn/T/.const_generator20210703-45810-1gxdya3:1:
	/usr/local/include/stdio.h:67:13: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	extern FILE *__stdinp;
	            ^
	/usr/local/include/stdio.h:67:13: note: insert '_Nullable' if the pointer may be null
	extern FILE *__stdinp;
	            ^
	              _Nullable 
	/usr/local/include/stdio.h:67:13: note: insert '_Nonnull' if the pointer should never be null
	extern FILE *__stdinp;
	            ^
	              _Nonnull 
	/usr/local/include/stdio.h:386:41: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	/usr/local/include/stdio.h:386:41: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	                                         _Nullable
	/usr/local/include/stdio.h:386:41: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	                                         _Nonnull
	/usr/local/include/stdio.h:386:55: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	/usr/local/include/stdio.h:386:55: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	                                                       _Nullable
	/usr/local/include/stdio.h:386:55: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	                                                       _Nonnull
	/usr/local/include/stdio.h:387:44: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	/usr/local/include/stdio.h:387:44: note: insert '_Nullable' if the pointer may be null
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	                                            _Nullable
	/usr/local/include/stdio.h:387:44: note: insert '_Nonnull' if the pointer should never be null
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	                                            _Nonnull
	/usr/local/include/stdio.h:388:41: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *));
	                                        ^
	/usr/local/include/stdio.h:388:41: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *));
	                                        ^
	                                         _Nullable
	/usr/local/include/stdio.h:388:41: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *));
	                                        ^
	                                         _Nonnull
	/usr/local/include/stdio.h:384:6: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	FILE    *funopen(const void *,
	        ^
	/usr/local/include/stdio.h:384:6: note: insert '_Nullable' if the pointer may be null
	FILE    *funopen(const void *,
	        ^
	          _Nullable 
	/usr/local/include/stdio.h:384:6: note: insert '_Nonnull' if the pointer should never be null
	FILE    *funopen(const void *,
	        ^
	          _Nonnull 
	13 errors generated.
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:131:in `block in calculate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in `calculate'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in `initialize'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `<module:Libc>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon.rb:16:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `block in update'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `open'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `update'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:143:in `each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by Gabsys** [comment]
Solved after running `sudo gem install -n /usr/local/bin cocoapods`
Not sure why I still need to install cocoapods with gem if I have already installed it with Homebrew O.O

**Comment by zabojad** [comment]
Same here: 

    LoadError - dlsym(0x209029740, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
    /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
