### ISSUE TITLE
Calling animateMarkerToCoordinate on animated marker causes app crash

### ISSUE THREAD

**Issue by andkom** [react-native-maps/react-native-maps#3913]
# Bug report

## Summary

I'm trying to animate marker position as shown in original example, but app crashes with `animateMarkerToCoordinate` call when I reload app. If I try to call `animateMarkerToCoordinate` in a working app it works OK.

## Environment info

```bash
react-native: 0.64.2
react: 17.0.1
react-native-maps: 0.29.2
```

## Steps to reproduce

LocationMarker.tsx:

```
import React, {useEffect, useRef, useState} from 'react';
import {Platform} from 'react-native';
import {AnimatedRegion, MarkerAnimated, LatLng} from 'react-native-maps';

const LocationMarker = ({coordinate}: {coordinate: LatLng}) => {
  const duration = 1000;
  const marker = useRef<MarkerAnimated>(null);
  const [coords] = useState<AnimatedRegion>(
    new AnimatedRegion({
      latitude: coordinate.latitude,
      longitude: coordinate.longitude,
      latitudeDelta: 0,
      longitudeDelta: 0,
    }),
  );

  useEffect(() => {
    if (Platform.OS === 'android') {
      if (marker.current) {
        marker.current.animateMarkerToCoordinate(coordinate, duration);
      }
    } else {
      coords
        .timing({
          latitude: coordinate.latitude,
          longitude: coordinate.longitude,
          duration,
          useNativeDriver: true,
        })
        .start();
    }
  }, [marker, coordinate, coords]);

  return <MarkerAnimated ref={marker} coordinate={coords} />;
};

export default LocationMarker;

```

App.tsx:

```
....
<MapView>
    <LocationMarker coordinate={coordinate} />
</MapView>
...
```

In the code above, coordinates are passed as variable, but app also crashes if I call `animateMarkerToCoordinate` with static values.

adb logcat:

```
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.airbnb.android.react.maps.AirMapMarker.interpolate(AirMapMarker.java:302)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.airbnb.android.react.maps.AirMapMarker$2.evaluate(AirMapMarker.java:311)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.airbnb.android.react.maps.AirMapMarker$2.evaluate(AirMapMarker.java:308)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1542)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.view.Choreographer.doFrame(Choreographer.java:693)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:873)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:193)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 18:52:30.428 28092 28092 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by likrot** [comment]
@andkom Try not to use `AnimatedRegion` with `animateMarkerToCoordinate`. Use your regular coordinates object instead.

**Comment by andkom** [comment]
@likrot in the example above I use regular coordinates with `animateMarkerToCoordinate`

**Comment by likrot** [comment]
@andkom No, you don't. I can see that you declare component with `coords` variable.

```js
return <MarkerAnimated ref={marker} coordinate={coords} />;
```

Replace it for android usecase with some initial value (do not use animatedRegion) and check. Should help.

**Comment by andkom** [comment]
@likrot unfortunately, It didn't help. 

Somehow using

```
setTimeout({
  marker.current.animateMarkerToCoordinate(...);
}, 0);
```

fixes crash

**Comment by chanphiromsok** [comment]
> @likrot unfortunately, It didn't help.
> 
> Somehow using
> 
> ```
> setTimeout({
>   marker.current.animateMarkerToCoordinate(...);
> }, 0);
> ```
> 
> fixes crash

work for me thansk you

**Comment by jakobbuis** [comment]
This is still a problem when animating a marker that was animated before. The first `animateMarkerToCoordinate()` works, the second one crashes.
