### ISSUE TITLE
Android Crash : Value for longitude cannot be cast from String to Double

### ISSUE THREAD

**Issue by fukemy** [react-native-maps/react-native-maps#4439]
### Summary

i got this error:Value for longitude cannot be cast from String to Double

this is my data:

{"lat": "37.4219983", "lng": "-122.084"}

It's work on IOS but crash on Android

### Reproducible sample code

```TSX
<MapView
                ref={mapRef}
                onMapLoaded={onMapReady}
                provider={PROVIDER_GOOGLE}
                style={{
                    borderRadius: 8,
                    width: 180,
                    height: 180,
                }}
                pointerEvents="none"
                pitchEnabled={false}
                zoomEnabled={false}
                zoomTapEnabled={false}
                scrollEnabled={false}
                rotateEnabled={false}
                zoomControlEnabled={false}
                liteMode
                onPress={() => {
                    OpenMap.show({
                        latitude: location.loc,
                        longitude: location.lng,
                      })
                }}
                initialRegion={{
                    latitude: location.lat,
                    longitude: location.lng,
                    latitudeDelta: 0.004,
                    longitudeDelta: 0.004,
                }}
                loadingEnabled>

                <Marker
                    coordinate={{
                        latitude: location.lat,
                        longitude: location.lng,
                    }}
                />
            </MapView>
```

### Steps to reproduce

set data to MapView

### Expected result

run normally

### Actual result

2022-09-14 20:43:50.021 4853-4853/com.vedaxlink E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vedaxlink, PID: 4853
    com.facebook.react.bridge.UnexpectedNativeTypeException: Value for longitude cannot be cast from String to Double
        at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:140)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:115)
        at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:151)
        at com.airbnb.android.react.maps.AirMapView.moveToRegion(AirMapView.java:491)
        at com.airbnb.android.react.maps.AirMapView.applyBridgedProps(AirMapView.java:478)
        at com.airbnb.android.react.maps.AirMapView.onMapReady(AirMapView.java:221)
        at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
        at com.google.android.gms.maps.internal.zzaq.zza(com.google.android.gms:play-services-maps@@18.0.0:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
        at android.os.Binder.transact(Binder.java:914)
        at db.b(:com.google.android.gms.dynamite_mapsdynamite@202414048@20.24.14 (040400-0):2)
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@202414048@20.24.14 (040400-0):2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

### React Native Maps Version

1.3.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.68.0

### What version of Expo are you using?

Not using Expo

### Device(s)

Android Emulator Pixel 2XL Api 30

**Comment by Simon-TechForm** [comment]
As the error message suggests, you shouldn't be passing lat and lng as strings :)

It should be:

```
{"lat": 37.4219983, "lng": -122.084}
```

**Comment by waqarakrambhuta** [comment]
coordinate={{
                  latitude: parseFloat(lat,
                  longitude: parseFloat(lng),
                }}
                
  worked for me...
