### ISSUE TITLE
MapView Marker causes "Element type is invalid: expected a string or class/function but got undefined" error in Expo 47 (react-native-maps 1.3.2)

### ISSUE THREAD

**Issue by vaibhavverma9** [react-native-maps/react-native-maps#4544]
### Summary

On Expo 47 (react-native-maps 1.3.2), MapView Marker causes "Element type is in invalid: expected a string (for built-in components) or a class/function (for composite components) but got undefined

This works perfectly fine in Expo 46! 

### Reproducible sample code

Please go to Expo Snack to reproduce bug:
https://snack.expo.dev/@vaibhavverma9/mapview-marker-causes-error-in-expo-v47

### Steps to reproduce

The issue is reproducible whenever you add a marker to the map view! You can see it in the Snack when you try under iOS. 

### Expected result

Expected result is a black pin in the middle of the map

### Actual result

Actual result is crash

<img width="263" alt="image" src="https://user-images.githubusercontent.com/12056493/205217115-a0bb3f75-e76c-45ff-95dd-16528d0a5544.png">

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 47

### Device(s)

iPhone 12, iPhone 8, Snack

**Comment by vaibhavverma9** [comment]
Hi I resolved the issue!

Instead of the following:
```
import MapView, { PROVIDER_GOOGLE, Callout }  from 'react-native-maps';
return (
<MapView.Marker .../>
)
```

You have to do the following:

```
import { Marker }  from 'react-native-maps';
return (
<Marker .../>
)
```

**Comment by delafuentej** [comment]
I have the same problem when I try to render MapView. "expo": "~51.0.12",  "react-native-maps": "^1.15.6". 
C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\App.js:13 Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at App.js:13.
    at App
    at withDevTools(App)
    at AppContainer (http://localhost:8081/index.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:29880:7)
printWarning @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react\cjs\react-jsx-dev-runtime.development.js:87
error @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react\cjs\react-jsx-dev-runtime.development.js:61
jsxWithValidation @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react\cjs\react-jsx-dev-runtime.development.js:1244
App @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\App.js:13
renderWithHooks @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:16305
mountIndeterminateComponent @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:20074
beginWork @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:21587
beginWork$1 @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:27426
performUnitOfWork @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:26557
workLoopSync @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:26466
renderRootSync @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:26434
performConcurrentWorkOnRoot @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:25738
workLoop @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\node_modules\scheduler\cjs\scheduler.development.js:266
flushWork @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\node_modules\scheduler\cjs\scheduler.development.js:239
performWorkUntilDeadline @ C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\node_modules\scheduler\cjs\scheduler.development.js:533
Show 14 more frames
Show less
C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    at createFiberFromTypeAndProps (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:28439:17)
    at createFiberFromElement (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:28465:15)
    at reconcileSingleElement (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:15750:23)
    at reconcileChildFibers (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:15808:35)
    at reconcileChildren (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:19167:28)
    at updateHostComponent (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:19924:3)
    at beginWork (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:4213:16)
    at invokeGuardedCallback (C:\Users\TxetxuSG\projekts\react-native\location-tracking-app\node_modules\react-dom\cjs\react-dom.development.js:4277:31)
Do you have any idea how I could fix it?
