### ISSUE TITLE
java.lang.OutOfMemoryError on showing the map

### ISSUE THREAD

**Issue by prnk04** [react-native-maps/react-native-maps#4597]
### Summary

We are using MapView to render the map, and getting error: Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 2534984 free bytes and 2475KB until OOM

Full Error: 
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 2534984 free bytes and 2475KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
       at sun.misc.Cleaner.create(Cleaner.java:132)
       at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:262)
       at android.graphics.Bitmap.<init>(Bitmap.java:160)
       at android.graphics.Bitmap.nativeCreateFromParcel(Bitmap.java)
       at android.graphics.Bitmap.-$$Nest$smnativeCreateFromParcel()
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2110)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2102)
       at azu.a(:com.google.android.gms.policy_maps_core_dynamite@224312102@224312102065.485900589.485900589:2)
       at com.google.android.gms.maps.model.internal.a.bo(:com.google.android.gms.policy_maps_core_dynamite@224312102@224312102065.485900589.485900589:8)
       at azt.onTransact(:com.google.android.gms.policy_maps_core_dynamite@224312102@224312102065.485900589.485900589:4)
       at android.os.Binder.transact(Binder.java:1164)
       at com.google.android.gms.internal.maps.zza.zzH(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.0.0:3)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.airbnb.android.react.maps.AirMapMarker.getIcon(AirMapMarker.java:458)
       at com.airbnb.android.react.maps.AirMapMarker.updateMarkerIcon(AirMapMarker.java:291)
       at com.airbnb.android.react.maps.AirMapMarker.updateCustomForTracking(AirMapMarker.java:283)
       at com.airbnb.android.react.maps.ViewChangesTracker.update(ViewChangesTracker.java:63)
       at com.airbnb.android.react.maps.ViewChangesTracker$1.run(ViewChangesTracker.java:23)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Reproducible sample code

```TSX
<MapView style={{ height: "100%", width: "100%", display: (listView) ? "none" : "flex", zIndex: -1 }}
                        
                        region={region}
                        showsMyLocationButton={true}
                        moveOnMarkerPress={false}

                        onPress={storeLocation}
                        onDoublePress={(e) => onMapPress(e)}
                        onPoiClick={(e) => onMapPress(e)}
                        onMarkerPress={() => storeLocation()}
                        onMarkerSelect={() => storeLocation()}
                    >

                        <Marker coordinate={coordinate}
                            // draggable
                            onPress={storeLocation}
                            onDragEnd={onMapPress}
                            style={{
                               
                            }}
                        // title = {userLocality + `, ` + userState}

                        >
                            {/* <PriceMarker amount={20} /> */}
                            <MarkerView></MarkerView>
                        </Marker>
                    </MapView>
```

### Steps to reproduce

The error is sporadic

### Expected result

The map should render without crashing the app

### Actual result

App is crashing

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.69.5

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung Galaxy S10(Android 10), Pixel 6(Android 13)

**Comment by Willham12** [comment]
**Device**
Brand: OnePlus
Model: OnePlus Nord
Orientation: Portrait
RAM free: 4.45 GB
Disk free: 27.55 GB

**Operating System**
Version: Android 12
Orientation: Portrait
Rooted:No


```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 168 byte allocation with 2530704 free bytes and 2471KB until OOM, target footprint 402653184, growth limit 402653184; giving up on allocation because <1% of heap free after GC.
       at ebr.a(ebr.java)
       at ebt.g(ebt.java:37)
       at ebt.<init>(ebt.java)
       at ebu.a(ebu.java:1)
       at ebv.j(ebv.java:10)
       at ebv.i(ebv.java)
       at dhx.<init>(dhx.java:1)
       at dmx.a(dmx.java:2)
       at com.google.maps.api.android.lib6.phoenix.an.B(an.java:23)
       at com.google.maps.api.android.lib6.phoenix.an.o(an.java:1)
       at com.google.maps.api.android.lib6.phoenix.an.i(an.java:19)
       at com.google.maps.api.android.lib6.impl.dw.b(dw.java:2)
       at com.google.maps.api.android.lib6.impl.du.Q(du.java)
       at com.google.maps.api.android.lib6.impl.du.t(du.java:5)
       at com.google.android.gms.maps.model.internal.s.bo(s.java:31)
       at azt.onTransact(azt.java:4)
       at android.os.Binder.transact(Binder.java:1084)
       at com.google.android.gms.internal.maps.zza.zzc(zza.java:7)
       at com.google.android.gms.internal.maps.zzv.zzs(zzv.java:9)
       at com.google.android.gms.maps.model.Marker.setIcon(Marker.java:15)
       at com.airbnb.android.react.maps.AirMapMarker.updateMarkerIcon(AirMapMarker.java:9)
       at com.airbnb.android.react.maps.AirMapMarker.updateCustomForTracking(AirMapMarker.java:6)
       at com.airbnb.android.react.maps.ViewChangesTracker.update(ViewChangesTracker.java:18)
       at com.airbnb.android.react.maps.ViewChangesTracker$1.run(ViewChangesTracker.java:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by lurui1029** [comment]
Still relevant

**Comment by cveklica** [comment]
Still a problem with latest version **1.11.3**.
Problem occurs on android version lower then compileSdkVersion.

On this version LATEST is default and there is no way to put it to LEGACY in RN code.

Workaround is to edit file: node_modules/react-native-maps/android/src/main/java/com/rnmaps/maps/MapModule.java
line 370: 
`MapsInitializer.Renderer.LATEST => MapsInitializer.Renderer.LEGACY` 

and then enable "latest renderer" in code with 
                  ` enableLatestRenderer().then(e => console.log(e));`
 //console.log just to show which one is selected, remove it

**Comment by TrustDec** [comment]
Still relevant，Is there any solution?

**Comment by chanphiromsok** [comment]
Still relevant ++

**Comment by PRANAVAN12** [comment]
Still relevant ++

**Comment by paul-wag** [comment]
Still relevant ++

**Comment by emaxedon** [comment]
Still relevant

**Comment by santiagoquintero95** [comment]
still relevant

**Comment by marcusviniciusf** [comment]
still relevant

**Comment by namtran-axonvibemta** [comment]
Still happened with react-native-maps": "1.17.3"

**Comment by namtran** [comment]
Still happened with react-native-maps": "1.17.3"

**Comment by gyenabubakar** [comment]
Can someone re-open this issue? This is still happening i am on `1.20.1`:

```
ERROR  Your app just crashed. See the error below.
java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 784576 free bytes and 766KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
  com.android.org.conscrypt.ConscryptEngine.transitionTo(ConscryptEngine.java:1829)
  com.android.org.conscrypt.ConscryptEngine.closeInbound(ConscryptEngine.java:465)
  com.android.org.conscrypt.ConscryptEngine.closeAll(ConscryptEngine.java:1345)
  com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:890)
  com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:744)
  com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:709)
  com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:907)
  com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:873)
  com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:846)
  okio.InputStreamSource.read(JvmOkio.kt:93)
  okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:153)
  okio.RealBufferedSource.request(RealBufferedSource.kt:211)
  okio.RealBufferedSource.require(RealBufferedSource.kt:204)
  okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
  okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
  okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
  okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
  okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
  okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
  okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
  java.lang.Thread.run(Thread.java:1119)
```

**Comment by jake-lindvall-lt** [comment]
Echoing still common on `1.20.1`, reason being this may be where many others are at is because it is the last stable version on old architecture, and is the one heavily recommended by Expo (at least 53)

**Comment by thisisadarshjaiswal** [comment]
Still relevant ++

**Comment by TrustDec** [comment]
我已经收到你的邮件啦~,表着急,待我仔细查看

**Comment by HarshitMadhav** [comment]
facing the same issue, its getting reported in crashlytics for multiple devices
using version 1.20.1

**Comment by Jesus2PQ** [comment]
Tengo el mismo problema

- expo: 53.0.23
- react-native-map:s 1.26.0


OutOfMemoryError
Failed to allocate a 24 byte allocation with 2142192 free bytes and 2091KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.


OutOfMemoryError
Failed to allocate a 24 byte allocation with 2142192 free bytes and 2091KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

kotlin.LazyKt__LazyJVMKt in lazy at line 35
com.facebook.react.bridge.ReadableNativeMap in <init> at line 36
com.facebook.react.bridge.ReadableNativeArray in importArray
com.facebook.react.bridge.ReadableNativeArray in localArray_delegate$lambda$0 at line 25
com.facebook.react.bridge.ReadableNativeArray in $r8$lambda$W1MHfICD9t4ojUIEnKgqaQ9xdQo
com.facebook.react.bridge.ReadableNativeArray$$ExternalSyntheticLambda0 in invoke
kotlin.SynchronizedLazyImpl in getValue at line 74
com.facebook.react.bridge.ReadableNativeArray in getLocalArray at line 23
com.facebook.react.bridge.ReadableNativeArray in size at line 39
com.rnmaps.maps.MapPolyline in setCoordinates at line 51
com.rnmaps.fabric.PolylineManager in setCoordinates at line 71
com.rnmaps.fabric.PolylineManager in setCoordinates at line 23
com.facebook.react.viewmanagers.RNMapsPolylineManagerDelegate in setProperty at line 28
com.facebook.react.uimanager.ViewManager in updateProperties at line 100
com.facebook.react.uimanager.ViewManager in createViewInstance at line 218
com.facebook.react.uimanager.ViewManager in createView at line 145
com.facebook.react.fabric.mounting.SurfaceMountingManager in createViewUnsafe at line 674
com.facebook.react.fabric.mounting.SurfaceMountingManager in preallocateView at line 1078
com.facebook.react.fabric.mounting.mountitems.PreAllocateViewMountItem in execute at line 38
com.facebook.react.fabric.mounting.MountItemDispatcher in executeOrEnqueue at line 370
com.facebook.react.fabric.mounting.MountItemDispatcher in dispatchMountItems at line 246
com.facebook.react.fabric.mounting.MountItemDispatcher in tryDispatchMountItems at line 122
com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback in doFrameGuarded at line 1396
com.facebook.react.uimanager.GuardedFrameCallback in doFrame at line 25
com.facebook.react.modules.core.ReactChoreographer in frameCallback$lambda$1 at line 59
com.facebook.react.modules.core.ReactChoreographer in $r8$lambda$nSkFhrr5T7rop_XKwzlLov4NLLw
com.facebook.react.modules.core.ReactChoreographer$$ExternalSyntheticLambda0 in doFrame
android.view.Choreographer$CallbackRecord in run at line 1899
android.view.Choreographer$CallbackRecord in run at line 1910
android.view.Choreographer in doCallbacks at line 1367
android.view.Choreographer in doFrame at line 1282
android.view.Choreographer$FrameDisplayEventReceiver in run at line 1870
android.os.Handler in handleCallback at line 995
android.os.Handler in dispatchMessage at line 103
android.os.Looper in loopOnce at line 273
android.os.Looper in loop at line 363
android.app.ActivityThread in main at line 10060
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 632
com.android.internal.os.ZygoteInit in main at line 975
