### ISSUE TITLE
Expo SDK 48 build failed: "Cannot add Google Maps to the project's AppDelegate because it's malformed"

### ISSUE THREAD

**Issue by TrustyTechSG** [react-native-maps/react-native-maps#4610]
### Summary

```
[stderr] Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
[stderr] Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
[stderr]     at /Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/ios/Maps.js:218:19
[stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:29)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:27)
[stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:27)
[stderr]     at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr]     at async evalModsAsync (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:204:25)
[stderr]     at async Object.compileModsAsync (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:124:10)
[stderr]     at async configureProjectAsync (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/prebuild/configureProjectAsync.js:54:15)
[stderr]     at async prebuildAsync (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js:83:9)
[stderr] error Command failed with exit code 1.
```

### Reproducible sample code

```TSX
This is a build time error
```

### Steps to reproduce

Run expo EAS build: eas build --platform ios

### Expected result

Build successfully

### Actual result

Build failed

### React Native Maps Version

1.4.0,1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.71.2

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone

**Comment by mariomurrent-softwaresolutions** [comment]
Same here

**Comment by RyanTG** [comment]
Would it be appropriate for you to report it to Expo? https://github.com/expo/expo/issues/new?assignees=&labels=needs+review&template=bug_report.yml

**Comment by mariomurrent-softwaresolutions** [comment]
> Would it be appropriate for you to report it to Expo? https://github.com/expo/expo/issues/new?assignees=&labels=needs+review&template=bug_report.yml

Maybe with an reproducible example.
@TrustyTechSG Does the issue still persist? Can you create a minimal reproducible example and open an issue in the Expo Directory?

**Comment by pchmn** [comment]
> > Would it be appropriate for you to report it to Expo? https://github.com/expo/expo/issues/new?assignees=&labels=needs+review&template=bug_report.yml
> 
> Maybe with an reproducible example.
> @TrustyTechSG Does the issue still persist? Can you create a minimal reproducible example and open an issue in the Expo Directory?

I created an [issue](https://github.com/expo/expo/issues/21282#issue-1590430094) in the expo repository with a reproducible example.
This issue is only present when using Google maps for me

**Comment by mariomurrent-softwaresolutions** [comment]
> > > Would it be appropriate for you to report it to Expo? https://github.com/expo/expo/issues/new?assignees=&labels=needs+review&template=bug_report.yml
> > 
> > Maybe with an reproducible example.
> > @TrustyTechSG Does the issue still persist? Can you create a minimal reproducible example and open an issue in the Expo Directory?
> 
> I created an [issue](https://github.com/expo/expo/issues/21282#issue-1590430094) in the expo repository with a reproducible example.
> This issue is only present when using Google maps for me

Awesome for the bug and example. Can you link the issue here as well?
For me it still persists.

**Comment by pchmn** [comment]
This issue is fixed with `@expo/config-plugins@6.0.1`, we can close it maybe

**Comment by zaidoooo** [comment]
https://docs.expo.dev/versions/latest/sdk/map-view/ 

Does this not work for you?

**Comment by mariomurrent-softwaresolutions** [comment]
It should be fixed with the config plugin update.
In addition I had to remove the expo cli version from package.json
