### ISSUE TITLE
App crashes with Could not copy bitmap to parcel blob error

### ISSUE THREAD

**Issue by deepakv-z14** [react-native-maps/react-native-maps#4813]
### Summary

App crashes with below traces

```
Fatal Exception: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2136)
       at com.google.android.gms.internal.maps.zzc.zzd(com.google.android.gms:play-services-maps@@18.0.0:3)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.rnmaps.maps.MapMarker.getIcon(MapMarker.java:460)
       at com.rnmaps.maps.MapMarker.updateMarkerIcon(MapMarker.java:291)
       at com.rnmaps.maps.MapMarker.updateCustomForTracking(MapMarker.java:283)
       at com.rnmaps.maps.ViewChangesTracker.update(ViewChangesTracker.java:63)
       at com.rnmaps.maps.ViewChangesTracker$1.run(ViewChangesTracker.java:23)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 ```

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

const LATITUDE_DELTA = 0.0002;
const LONGITUDE_DELTA = 0.009;

export default function App() {
  return (
    <MapView
      ref={mapRef}
      toolbarEnabled={false}
      onMapReady={onLayout}
      zoomEnabled={false}
      scrollEnabled={false}
      pitchEnabled={false}
      provider={PROVIDER_GOOGLE}
      moveOnMarkerPress={false}
      style={{ ...StyleSheet.absoluteFillObject }}
      showsMyLocationButton={false}
      maxZoomLevel={18}
      minZoomLevel={14}
      mapPadding={{
        top: 0,
        right: 20,
        bottom: 0,
        left: 20,
      }}
      initialRegion={{
        latitude: 37.774929,
        longitude: -122.419418,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      }}>
      <Marker coordinate={{ latitude: 37.774929, longitude: -122.419418 }}>
        <Image source={{ uri: 'imageurl' }} style={{ height: 20, width: 20 }} />
      </Marker>
    </MapView>
  );
}
```

### Steps to reproduce

Run app with above code

### Expected result

App should not crash

### Actual result

App crashes on some devices

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.12

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung  Galaxy A21s

**Comment by CristianBarbosa01** [comment]
Was solved?

**Comment by deepakv-z14** [comment]
@CristianBarbosa01 Yes, pre-bundling the marker images solved it for me.

**Comment by jeovabah** [comment]
Can you give me a code example of how you did this? @deepakv-z14

**Comment by deepakv-z14** [comment]
If you are having dynamic link you can try downloading the image before rendering the map

My implementation looks like: 
```
import CustomerMarker from '../../assets/svg/custom.svg';

 <Marker
      coordinate={{
        latitude: coordinate?.latitude ? coordinate?.latitude : 0,
        longitude: coordinate?.longitude ? coordinate?.longitude : 0,
      }}
      tracksViewChanges={tracksViewChanges}
    >
    <CustomMarker
              style={styles.markerStyle}
              onLayout={stopTrackingViewChanges}
            />
    </Marker>

**Comment by jeovabah** [comment]
Thanks my friend. You save my job!!!!!!!
