### ISSUE TITLE
maps not work in Realme 11 Pro+ 5G & Huawei Y9 Prime 2019

### ISSUE THREAD

**Issue by Youssef-Durgham** [react-native-maps/react-native-maps#4831]
### Summary

the error for crash report from firebase is
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude
       at com.facebook.react.bridge.ReadableNativeMap.getValue(:27)
       at com.facebook.react.bridge.ReadableNativeMap.getValue()
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(:2)
       at com.rnmaps.maps.MapView.moveToRegion(MapView.java:5)
       at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:5)
       at com.rnmaps.maps.MapView.onMapReady(MapView.java:90)
       at com.google.android.gms.maps.zzaf.zzb(zzaf.java:7)
       at com.google.android.gms.maps.internal.zzaq.zza(zzaq.java:31)
       at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:921)
       at m.fn.c(:com.google.android.gms.dynamite_mapsdynamite@233116028@23.31.16 (100400-0):8)
       at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@233116028@23.31.16 (100400-0):19)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### Reproducible sample code

```TSX
<MapView
            style={styles.map}
            ref={mapRef}
            onPress={handlePress}
            onPoiClick={event => {
              setLocation(event.nativeEvent.coordinate);
              AsyncStorage.setItem(
                'userLocation',
                JSON.stringify(event.nativeEvent.coordinate),
              );
            }}
            provider={PROVIDER_GOOGLE}
            initialRegion={initialRegion}
            onRegionChangeComplete={onRegionChangeComplete}>
            {location && (
              <MemoMarker coordinate={location} tracksViewChanges={false} />
            )}
          </MapView>
```

### Steps to reproduce

when try open the map app crash and got this error
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude
       at com.facebook.react.bridge.ReadableNativeMap.getValue(:27)
       at com.facebook.react.bridge.ReadableNativeMap.getValue()
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(:2)
       at com.rnmaps.maps.MapView.moveToRegion(MapView.java:5)
       at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:5)
       at com.rnmaps.maps.MapView.onMapReady(MapView.java:90)
       at com.google.android.gms.maps.zzaf.zzb(zzaf.java:7)
       at com.google.android.gms.maps.internal.zzaq.zza(zzaq.java:31)
       at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:1188)
       at m.fh.c(:com.google.android.gms.dynamite_mapsdynamite@233116045@23.31.16 (190408-0):8)
       at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@233116045@23.31.16 (190408-0):19)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### Expected result

it works on others devices correct but on theses two devices it not

### Actual result

app crash when try open the map

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.6

### What version of Expo are you using?

Not using Expo

### Device(s)

Realme 11 Pro+ 5G, Huawei Y9 Prime 2019

**Comment by haiderTkxel** [comment]
Anyone finds the solution?

**Comment by Youssef-Durgham** [comment]
Yes the problem in the @react-native-community/geolocation
 use react-native-geolocation-service instead and it will works fine

**Comment by Youssef-Durgham** [comment]
The library of @react-native-community/geolocation not supporting android api 28 and above it’s in there documentation so use react-native-geolocation-service will fix it.

**Comment by haiderTkxel** [comment]
@Youssef-Durgham Crash does not go away. Can I miss something?

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

**Comment by Youssef-Durgham** [comment]
here is my build script 
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        googleServicesVersion = '4.3.15'
        firebaseBomVersion = "31.3.0"
        kotlin_version = '1.6.10'

        googlePlayServicesVersion = "18.0.0"

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by haiderTkxel** [comment]
@Youssef-Durgham Problem solved, but now blank google map is displaying.

**Comment by haiderTkxel** [comment]
@Youssef-Durgham After adding pitch and heading prop in 'initialCamera' object, the crash does not happen but blank map is displaying.

**Comment by Youssef-Durgham** [comment]
Can you share the code to see it

**Comment by Youssef-Durgham** [comment]
> @Youssef-Durgham After adding pitch and heading prop in 'initialCamera' object, the crash does not happen but blank map is displaying.

Can you share the code to see it

**Comment by haiderTkxel** [comment]
> Can you share the code to see it


const initialCamera = {
    center: {
      latitude: 30.202548,
      longitude: 71.499398,
    },
    pitch: 85,
    heading: 30,
    zoom: 12,
  };

<MapView
          style={styles.mapView}
          provider={PROVIDER_GOOGLE}
          initialRegion={currentLocation}
          showsUserLocation={true}
          initialCamera={initialCamera}
          mapType={Platform.OS == "android" ? "none" : "standard"}
        >
          {orders.map((order, index) => (
            <Marker
              key={index}
              // image={icons.marker}
              coordinate={order.coordinate}
              // title={`Waypoint ${index + 1}`}
              onPress={() => {
                (order.status === Strings.new ||
                  order.status === Strings.inProgress) &&
                  handlePressOnMarker(order);
              }}
            >
              <MarkerWithText order={order} />
            </Marker>
          ))}

          {/* Render polyline */}

          <Polyline
            coordinates={routeCoordinates}
            strokeColor={theme.colors.blue4}
            strokeWidth={4}
            lineDashPattern={[15, 15]}
          />
        </MapView>

**Comment by asaadxheikh** [comment]
I'm getting this crash on firebase crashlytics for some devices including s24 ultra but not all the devices.


`Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:151)
       at com.rnmaps.maps.MapView.moveToRegion(MapView.java:523)
       at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:505)
       at com.rnmaps.maps.MapView.onMapReady(MapView.java:248)
       at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
       at com.google.android.gms.maps.internal.zzaq.zza(com.google.android.gms:play-services-maps@@18.0.0:5)
       at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
       at android.os.Binder.transact(Binder.java:1219)
       at m.bcv.c(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:8)
       at com.google.maps.api.android.lib6.impl.ch.run(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:17)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

The Crash is happing after boot
