### ISSUE TITLE
App crashes on Android when upgrading to 1.10.1 from 1.7.1

### ISSUE THREAD

**Issue by alfredvaa** [react-native-maps/react-native-maps#4957]
### Summary

Upgraded Expo from 49 to 50 and at the same time updated react-native-maps from 1.7.1 to 1.10.1. The app now crashes when opening a view with a map. I downgraded to 1.9.1 which did not work either. I downgraded again to 1.8.1 and that version seems to work.

### Reproducible sample code

```TSX
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
    at java.util.Objects.checkIndex(Objects.java:359)
    at java.util.ArrayList.get(ArrayList.java:434)
    at com.google.maps.api.android.lib6.lite.v.a(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):3)
    at com.google.maps.api.android.lib6.lite.x.b(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):1)
    at com.google.maps.api.android.lib6.lite.k.onDraw(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):8)
    at android.view.View.draw(View.java:23889)
    at android.view.View.buildDrawingCacheImpl(View.java:23153)
    at android.view.View.buildDrawingCache(View.java:23013)
    at android.view.View.draw(View.java:23612)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
    at android.view.View.updateDisplayListIfDirty(View.java:22747)
    at android.view.View.draw(View.java:23620)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
    at android.view.View.updateDisplayListIfDirty(View.java:22747)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
    at android.view.View.updateDisplayListIfDirty(View.java:22712)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
    at android.view.Choreographer.doCallbacks(Choreographer.java:952)
    at android.view.Choreographer.doFrame(Choreographer.java:882)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8177)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Steps to reproduce

Upgrade Expo from 49 to 50 and react-native-maps from 1.7.1 to 1.10.1

### Expected result

No crash

### Actual result

Crash

### React Native Maps Version

1.10.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.2

### What version of Expo are you using?

SDK 48

### Device(s)

Pixel_6_API_34

### Additional information

Expo SDK is actually 50 but it is not possible to choose in the bug report view.

**Comment by chanphiromsok** [comment]
> Hi @alfredvaa thanks for reporting this. Did you try to run it with clean project or with minimum dependencies needed for your project? Or maybe you have a custom config, or you are using some methods on initial render of the map? Can you post the component in which you are using MapView?
> 
> I've just built a project with below dependencies and code and it works fine.
> 
> ```
> "dependencies": {
>     "expo": "~50.0.4",
>     "expo-status-bar": "~1.4.4",
>     "nativewind": "^2.0.11",
>     "react": "18.2.0",
>     "react-native": "0.73.2",
>     "react-native-dotenv": "^3.4.9",
>     "react-native-maps": "^1.10.1",
>     "tailwindcss": "3.3.2"
>   },
> ```
> 
> ```js
> import MapView from "react-native-maps"
> 
> export default function NavigationScreen() {
>     return (
>                 <MapView
>                     minZoomLevel={20}
>                     initialCamera={{
>                         center: {
>                           latitude: 37.78825,
>                           longitude: -122.4324,
>                         },
>                         pitch: 0,
>                         heading: 0,
>                         altitude: 1000,
>                         zoom: 10,
>                       }}
>                     style={{ width: '100%', height: '100%' }}
>                 
>                 >
>                 </MapView>
>     );
> }
> ```

I  got a freeze map  view when upgrading to 1.10.2  with googlePlayService 21.0.1
- MapView can not move at all for animateRegion it works

**Comment by giorgio79** [comment]
Possibly related issue https://issuetracker.google.com/issues/342316801
