### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Listener must not be null

### ISSUE THREAD

**Issue by Willham12** [react-native-maps/react-native-maps#4978]
### Summary

```
Fatal Exception: java.lang.NullPointerException: Listener must not be null
       at com.google.android.gms.common.internal.Preconditions.checkNotNull(Preconditions.java:9)
       at com.google.android.gms.common.api.internal.ListenerHolders.createListenerKey(ListenerHolders.java:2)
       at com.google.android.gms.location.FusedLocationProviderClient.removeLocationUpdates(FusedLocationProviderClient.java:6)
       at com.rnmaps.maps.FusedLocationSource.deactivate(FusedLocationSource.java:4)
       at com.google.android.gms.maps.zzs.deactivate(zzs.java:2)
       at com.google.android.gms.maps.internal.zzj.zza(zzj.java:8)
       at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:1064)
       at com.google.android.gms.maps.internal.ILocationSourceDelegate$Stub$Proxy.deactivate(ILocationSourceDelegate.java:121)
       at org.microg.gms.maps.mapbox.SourceLocationEngine.removeLocationUpdates(SourceLocationEngine.kt:41)
       at org.microg.gms.maps.mapbox.GoogleMapImpl.updateLocationEngineListener(GoogleMap.kt:423)
       at org.microg.gms.maps.mapbox.GoogleMapImpl.setLocationSource(GoogleMap.kt:436)
       at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(IGoogleMapDelegate.java:474)
       at org.microg.gms.maps.mapbox.GoogleMapImpl.onTransact(GoogleMap.kt:871)
       at android.os.Binder.transact(Binder.java:1064)
       at com.google.android.gms.internal.maps.zza.zzc(zza.java:7)
       at com.google.android.gms.maps.internal.zzg.setLocationSource(zzg.java:9)
       at com.google.android.gms.maps.GoogleMap.setLocationSource(GoogleMap.java:16)
       at com.rnmaps.maps.MapView$15.onHostResume(MapView.java:29)
       at com.facebook.react.bridge.ReactContext$1.run(:17)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage()
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
### Reproducible sample code

```TSX
<MapView
  initialRegion={{
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
/>
```

### Steps to reproduce

On start

### Expected result

no crash

### Actual result

crash

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Volla Phone Android 12

**Comment by mateki0** [comment]
Hi @Willham12 thanks for reporting this problem. I can't reproduce it, maybe it's the case of your phone and it's OS but I don't have access to this or similar device. Can you try to update react-native-maps to the newest version and check if it helps?
