### ISSUE TITLE
Could not copy bitmap to parcel blob crush in Moto G 5G - 2024 android version 14

### ISSUE THREAD

**Issue by minhajul-islam** [react-native-maps/react-native-maps#5137]
### Summary

Fatal Exception: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2278)
       at com.google.android.gms.internal.maps.zzc.zzd(com.google.android.gms:play-services-maps@@18.2.0:3)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.2.0:2)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.2.0:2)
       at com.rnmaps.maps.MapMarker.getIcon(MapMarker.java:464)
       at com.rnmaps.maps.MapMarker.updateMarkerIcon(MapMarker.java:295)
       at com.rnmaps.maps.MapMarker.updateCustomForTracking(MapMarker.java:287)
       at com.rnmaps.maps.ViewChangesTracker.update(ViewChangesTracker.java:64)
       at com.rnmaps.maps.ViewChangesTracker$1.run(ViewChangesTracker.java:22)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

### Reproducible sample code

```TSX
<Marker {...props} anchor={{ x: 0.5, y: 0.5 }} >
      <View
        style={{
          justifyContent: 'center',
          backgroundColor: '#0000FF30',
          width: 64,
          height: 64,
          borderRadius: 32,
        }}>
        <View
          style={{
            alignSelf: 'center',
            backgroundColor: '#0000FF',
            width: 10,
            height: 10,
            borderRadius: 5,
            borderColor: 'white',
            borderWidth: 1,
          }}
        />
      </View>
    </Marker>
```

### Steps to reproduce

Could not copy bitmap to parcel blob crush

### Expected result

Could not copy bitmap to parcel blob crush

### Actual result

Could not copy bitmap to parcel blob crush

### React Native Maps Version

1.15.4

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.9

### What version of Expo are you using?

Not using Expo

### Device(s)

Moto G 5G - 2024

### Additional information

Could not copy bitmap to parcel blob crush

**Comment by ssommelet21** [comment]
Hi minhajul-islam, check this topic here, same as you :

https://github.com/react-native-maps/react-native-maps/issues/4813
