### ISSUE TITLE
New arch crash when using mapRef.current.getCamera() on 1.15.5 or newer on Android

### ISSUE THREAD

**Issue by puelocesar** [react-native-maps/react-native-maps#5182]
### Summary

After https://github.com/react-native-maps/react-native-maps/pull/5061 got merged, this crash started appearing when using `mapRef.current?.getCamera()`:

```
E  Exception thrown when executing UIFrameGuarded
java.util.ConcurrentModificationException
          at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
          at java.util.ArrayList$Itr.next(ArrayList.java:982)
```

### Reproducible sample code

```TSX
import MapView from 'react-native-maps';
import React, { useRef } from 'react';
import { registerRootComponent } from 'expo';
export default registerRootComponent(() => {
  const ref = useRef();

  return (
    <MapView
      ref={ref}
      onRegionChange={() => {
        const cam = ref.current?.getCamera();
        console.log(cam?.heading);
      }}
      style={{ flex: 1 }}
    />
  );
});
```

### Steps to reproduce

- Enable bridgeless mode
- Update to 1.15.5 or newer
- keep scrolling the web view, eventually, getting the camera will throw this error 

### Expected result

No crash

### Actual result

Native crash, here's the full log from Logical

```
2024-10-11 18:41:55.389   984-984   BufferQueueProducer     surfaceflinger                       I  [com.argonav/com.argonav.MainActivity#6946](this:0xb400007dce648ae8,id:-1,api:0,p:-1,c:984) queueBuffer: fps=28.63 dur=1012.83 max=77.55 min=16.60
2024-10-11 18:41:55.487 28450-28845 TrafficStats            com.argonav                          D  tagSocket(286) with statsTag=0xffffffff, statsUid=-1
2024-10-11 18:41:55.489 28450-28844 TrafficStats            com.argonav                          D  tagSocket(309) with statsTag=0xffffffff, statsUid=-1
2024-10-11 18:41:55.635 28450-28461 com.argonav             com.argonav                          I  Background concurrent copying GC freed 242203(10064KB) AllocSpace objects, 220(8880KB) LOS objects, 37% free, 39MB/63MB, paused 419us,328us total 303.296ms
2024-10-11 18:41:55.842 28450-28460 com.argonav             com.argonav                          I  Compiler allocated 5539KB to compile void m.edl.V(m.ehn, m.eyj, android.content.res.Resources, m.efp, m.eqc, boolean, m.dgf, java.util.Map, boolean, boolean, boolean)
2024-10-11 18:41:55.955 28450-28827 ProxyAndro...gerBackend com.argonav                          W  Too many Flogger logs received before configuration. Dropping old logs.
2024-10-11 18:41:55.962 28450-28835 ProxyAndro...gerBackend com.argonav                          W  Too many Flogger logs received before configuration. Dropping old logs.
2024-10-11 18:41:56.079 28450-28450 unknown:FabricUIManager com.argonav                          E  Exception thrown when executing UIFrameGuarded
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:982)
                                                                                                    	at com.facebook.react.fabric.internal.interop.InteropUIBlockListener.didMountItems(InteropUiBlockListener.kt:72)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener.didMountItems(FabricUIManager.java:1217)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:300)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:107)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1321)
                                                                                                    	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:32)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1481)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1492)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1066)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:956)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1466)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:207)
                                                                                                    	at android.os.Looper.loop(Looper.java:296)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8227)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
2024-10-11 18:41:56.080 28450-28450 unknown:BridgelessReact com.argonav                          W  ReactHost{0}.handleHostException(message = "null")
2024-10-11 18:41:56.082 28450-28450 DevLauncher             com.argonav                          E  Exception in native call from JS
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:982)
                                                                                                    	at com.facebook.react.fabric.internal.interop.InteropUIBlockListener.didMountItems(InteropUiBlockListener.kt:72)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener.didMountItems(FabricUIManager.java:1217)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:300)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:107)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1321)
                                                                                                    	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:32)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1481)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1492)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1066)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:956)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1466)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:207)
                                                                                                    	at android.os.Looper.loop(Looper.java:296)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8227)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
2024-10-11 18:41:56.094   984-1382  BufferQueueDebug        surfaceflinger                       E  [ActivityRecord{f02e3cb u0 com.argonav/expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity#6956](this:0xb400007dce626828,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ActivityRecord{f02e3cb u0 com.argonav/expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity#6956'
```

### React Native Maps Version

1.15.5

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.1

### What version of Expo are you using?

SDK 48

### Device(s)

Any Android phone, I did on Motorola Moto g24 and Emulator

**Comment by salah-ghanim** [comment]
@puelocesar thanks for reporting this. I will try to analyze it deeper but from a first look it seems like a crash in Fabric itself (I don't see any react-native-maps) specific code

**Comment by Ayoubdesigner101** [comment]
can any one show this question https://stackoverflow.com/questions/79133414/invariant-violationnew-nativeeventemitter-requires-a-non-null-argument-js-e

**Comment by TyAzur** [comment]
Background concurrent copying GC freed 15MB AllocSpace bytes, 14(1864KB) LOS objects, 31% free, 51MB/75MB, paused 73us,166us total 218.258ms
2024-10-29 20:05:05.478 22656-22656 Choreographer           com.tyazur.CheckinWise               D  still have 9 traversal callbacks
2024-10-29 20:05:17.176 22656-23054 ProxyAndro...gerBackend com.tyazur.CheckinWise               W  Too many Flogger logs received before configuration. Dropping old logs.
2024-10-29 20:05:17.221 22656-23054 ProxyAndro...gerBackend com.tyazur.CheckinWise               W  Too many Flogger logs received before configuration. Dropping old logs.
2024-10-29 20:05:17.266 22656-23054 ProxyAndro...gerBackend com.tyazur.CheckinWise               W  Too many Flogger logs received before configuration. Dropping old logs.
2024-10-29 20:05:17.311 22656-23054 ProxyAndro...gerBackend com.tyazur.CheckinWise               W  Too many Flogger logs received before configuration. Dropping old logs.

**Comment by puelocesar** [comment]
@TyAzur seems unrelated to the reported issue

**Comment by salah-ghanim** [comment]
@puelocesar can you please test again with a newer version of react-native

I see some work being done around 
[ReactChoreographer](https://github.com/facebook/react-native/blob/3e27ef1f6e024bba8725a3bd64e2648ffd6af496/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactChoreographer.kt)

for example
https://github.com/facebook/react-native/commit/46fc9d9a2d48af0f00f061b55f9d6cbced162dae


from the crash itself it seems like a "dirty state" in the native part and not sure really if we should do something about it.
