### ISSUE TITLE
ANR std::__ndk1::condition_variable::wait

### ISSUE THREAD

**Issue by trungledangAxonActive** [react-native-maps/react-native-maps#5304]
### Summary

We're currently facing the number of ANRs on Android and not able to reproduce this one after many attempts. We got this message 
```
std::__ndk1::condition_variable::wait
ANR triggered by slow operations in blamed thread
split_config.arm64_v8a.apk
```
We've dived into the stack trace and mostly see the logs showing  
`:com.google.android.gms.policy_maps_core_dynamite`
It only happens on Android 14 and Android 15

I'm not sure this issue related to google map but this is the only thing that is suspicious at the moment. Hence, I would really appreciate that you guys - the great maintainers can give us some suggestions to see whether it really comes from the map. We would really appreciate that.

Here's our crashlytic dashboard looks like: 
![image](https://github.com/user-attachments/assets/73a6a771-20ec-422c-9918-ba0c8d0f400b)

Here's the stack trace that causes the ANR: 
```
# Crashlytics - Stack trace
# Application: ***
# Platform: android
# Version: 3.14.2 (861)
# Issue: 8b04e0ee7a842c3d287ee248af59fffa
# Session: 676334C301A90001502D3531B48A958E_DNE_0_v2
# Date: Thu Dec 19 2024 03:47:21 GMT+0700 (Indochina Time)

main (blocked):tid=1 systid=20525 | waiting to lock <0x0606d7f7> (java.util.ArrayList) held by thread 186
       at m.dqo.f(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:3)
       at com.google.maps.api.android.lib6.phoenix.bc.P(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:275)
       at com.google.maps.api.android.lib6.impl.cg.bh(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:23)
       at com.google.maps.api.android.lib6.impl.cg.ab(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:36)
       at com.google.android.gms.maps.internal.j.bs(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:292)
       at m.aya.onTransact(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:21)
       at android.os.Binder.transact(Binder.java:1219)
       at com.google.android.gms.internal.maps.zza.zzJ(com.google.android.gms:play-services-maps@@18.2.0:8)
       at com.google.android.gms.maps.internal.zzg.setIndoorEnabled(com.google.android.gms:play-services-maps@@18.2.0:12)
       at com.google.android.gms.maps.GoogleMap.setIndoorEnabled(com.google.android.gms:play-services-maps@@18.2.0:3)
       at com.rnmaps.maps.MapManager.setShowIndoors(MapManager.java:2)
       at java.lang.reflect.Method.invoke(Native method)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:1)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:1)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:1)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:10)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:10)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:141)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.kt)
       at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:46)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
       at android.view.Choreographer.doFrame(Choreographer.java:1069)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8918)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

mqt_native_modules (blocked):tid=66 systid=20664 | waiting to lock <0x06c16664> (com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager) held by thread 1
       at com.facebook.react.uimanager.NativeViewHierarchyManager.getRootViewNum(NativeViewHierarchyManager.java)
       at com.facebook.react.uimanager.UIImplementation.getRootViewNum(UIImplementation.java:1)
       at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:70)
       at com.facebook.react.uimanager.ReanimatedUIManager.onBatchComplete(ReanimatedUIManager.java)
       at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:24)
       at com.facebook.react.bridge.CatalystInstanceImpl$InstanceCallback.lambda$onBatchComplete$0(CatalystInstanceImpl.java:4)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:1012)

androidmapsapi-Background_3 (blocked):tid=181 systid=20884 | waiting to lock <0x0606d7f7> (java.util.ArrayList) held by thread 186
       at m.dqw.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:10)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at m.bup$a.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:19)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at m.bve.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:40)
       at java.lang.Thread.run(Thread.java:1012)

androidmapsapi-Background_6 (blocked):tid=184 systid=20887 | waiting to lock <0x0606d7f7> (java.util.ArrayList) held by thread 186
       at m.dqo.i(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:3)
       at m.drw.n(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:39)
       at com.google.maps.api.android.lib6.phoenix.ba.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:78)
       at com.google.maps.api.android.lib6.impl.ee.g(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:570)
       at com.google.maps.api.android.lib6.impl.ef.k(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:126)
       at com.google.maps.api.android.lib6.impl.ef.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:1)
       at m.dhp.c(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:3)
       at m.dhp.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:13)
       at m.dhp.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:1)
       at m.dit.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:36)
       at m.ekp.c(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:10)
       at m.dbs.h(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:32)
       at m.ayp.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:33)
       at m.bxd.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:16)
       at m.bxa.e(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:6)
       at m.bxa.f(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:46)
       at m.bxa.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:197)
       at m.btw.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:8)
       at m.btm.f(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:293)
       at m.btj.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:95)
       at m.bsx.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:29)
       at m.bhj.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:87)
       at m.gti.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:30)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at m.bup$a.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:19)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at m.bve.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:40)
       at java.lang.Thread.run(Thread.java:1012)

androidmapsapi-Background_8 (blocked):tid=186 systid=20889 | waiting to lock <0x0b67ace7> (m.dit) held by thread 184
       at m.dit.a(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:1)
       at m.eoy.r(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:19)
       at m.edq.z(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:10)
       at m.dqw.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:31)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at m.bup$a.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:19)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at m.bve.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:40)
       at java.lang.Thread.run(Thread.java:1012)

GL-Map (blocked):tid=190 systid=20897 | waiting to lock <0x037d3094> (m.ekp) held by thread 184
       at m.ekp.d(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:1)
       at m.ent.n(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:100)
       at m.exp.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:802)

androidmapsapi-DataRequestDispatcher-1 (blocked):tid=218 systid=20943 | waiting to lock <0x037d3094> (m.ekp) held by thread 184
       at m.ekp.c(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:7)
       at m.dbs.h(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:32)
       at com.google.maps.api.android.lib6.phoenix.bb.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:3)
       at com.google.maps.api.android.lib6.impl.ef.j(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:28)
       at com.google.maps.api.android.lib6.impl.gr.f(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:33)
       at com.google.maps.api.android.lib6.impl.gq.j(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:199)
       at com.google.maps.api.android.lib6.drd.r.run(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:355)
       at java.lang.Thread.run(Thread.java:1012)
```
 
 

### Reproducible sample code

```TSX
No Sample Code
```

### Steps to reproduce

It happens for most of the users open the app. The ANR will happen. 

### Expected result

Should not face ANR 

### Actual result

Face ANR

### React Native Maps Version

1.17.3

### What platforms are you seeing the problem on?

Android

### React Native Version

0.75.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Android 14, Android 15

**Comment by ssommelet21** [comment]
Hello,

There's a lot of talk about "**setIndoorEnabled**".

Perhaps you could set this boolean to false for testing:

https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md

<MapView
  ...
  showsIndoors={**false**} // Indoor Maps disabled
/>

**Comment by trungledangAxonActive** [comment]
Thanks @ssommelet21 , Sorry for replying late. I will try this one to see if it's working. Much appreciate. 
Could you please send me some thread that talks about this issue, I've searched some but didn't see any threads related to "setIndoorEnabled". Thanks a lot.

**Comment by trungledangAxonActive** [comment]
Hi @ssommelet21, We've checked that we already set the `showsIndoors` to false since the beginning. Hence, I believe that this might not come from this property. Do you have any other suggestions? Thank you so much. 
![image](https://github.com/user-attachments/assets/9af7698b-6e44-4bd0-8864-4d43fee221c9)

**Comment by trungledangAxonActive** [comment]
Still relevant
